### ISSUE TITLE
Useful for games? 

### ISSUE THREAD

**Issue by trusktr** [3mcd/web-udp#32]
Would this be useful for real-time game communication, f.e. making a browser-based first-person shooter? How would it compare to using WebSockets?

**Comment by 3mcd** [comment]
Hey @trusktr, so sorry I didn't see your question until now. I assume you may already have an answer, but yes, this library can be used to connect clients with a game server for fast-paced, multiplayer communication. The salient benefit of WebRTC (what web-udp uses) over TCP (WebSockets) is that it doesn't suffer from head-of-line blocking, a phenomenon that can manifest as stuttering/fast-forwarding in games that send a lot of positional data.

Of course, you get a lot of guarantees with TCP that you may want to implement yourself on top of UDP (like ordering and optional reliability). So it's probably best to try both and see how your game actually performs before downgrading to a less reliable transport.

You may also want to look into https://www.w3.org/TR/webtransport. It offers similar benefits to WebRTC data channels without all the bloat that WebRTC brings (audio/video etc).
